### PR TITLE
Request

### PR DESCRIPTION
**Pull request by agiani99**
Hi Robin,
I am using your code and wonder two things:
1) ULF (i.e. frequences below 0.003Hz are not taken into account? should we?
2) why SD1/SD2 has been defined as SD2/SD1?
Best
Andrea

### CODE REVIEW

**Comment by clecoued** [comment]
hi @agiani99, 
it would be a good idea to support ULF (<0.003Hz). The only limitation is that we required a RR-interval list recording for more than 24h (about 90 000 RR samples) to compute a relevant values.

**Comment by clecoued** [comment]
Regarding the SD1 / SD2, you are right. I opened a bug issue and we are going to fix this quickly -> https://github.com/Aura-healthcare/hrvanalysis/issues/17

**Comment by agiani99** [comment]
Hallo Clement,
Thanks for reply.
I agree. In case could we always check if(df['First_columnn_label'].count <20000) ....
Best
Andrea

 

-----Ursprüngliche Nachricht-----
Von: Clément Le Couedic [mailto:notifications@github.com] 
Gesendet: Montag, 12. August 2019 16:58
An: Aura-healthcare/hrvanalysis <hrvanalysis@noreply.github.com>
Cc: Andrea Zaliani <Andrea.Zaliani@ime.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Aura-healthcare/hrvanalysis] Request (#15)

hi @agiani99 <https://github.com/agiani99> , it would be a good idea to support ULF (<0.003Hz). The only limitation is that we required a RR-interval list recording for more than 24h (about 90 000 RR samples) to compute a relevant values.

**Comment by agiani99** [comment]
Hi Clement,
Beside what you correctly mentioned, in case of a 24hrs recording, there is a need to adjust also the ranges of filtered RR (NN) as I saw amazing differences using 2000-3000 as maximum allowed vs 5000-6000 in data preparation sections. 
Best
Andrea
 

-----Ursprüngliche Nachricht-----
Von: Clément Le Couedic [mailto:notifications@github.com] 
Gesendet: Montag, 12. August 2019 16:58
An: Aura-healthcare/hrvanalysis <hrvanalysis@noreply.github.com>
Cc: Andrea Zaliani <Andrea.Zaliani@ime.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Aura-healthcare/hrvanalysis] Request (#15)

hi @agiani99 <https://github.com/agiani99> , it would be a good idea to support ULF (<0.003Hz). The only limitation is that we required a RR-interval list recording for more than 24h (about 90 000 RR samples) to compute a relevant values.

**Comment by clecoued** [comment]
Hi @agiani99,
We know that outliers NN intervals ( > 3000 ms) may have an impact on the computation of the frequency features. 
We choose to set the upper boundary to 2000 - 3000 ms (heart rate at 20 bpm)because it is the limit of what is physiologically acceptable. Higher NN interval would not make sense.

**Comment by robinchampseix** [comment]
Hi Andrea,

Thank you for your message and sorry for the late reply. There is no standard to our best knowledge regarding which ratio to use (SD2/SD1 vs SD1/SD2). Each feature could be used interchangeably as the 2 ratios are simply inverse numbers.

As Clement previously stated, it is very hard to have enough quality data to provide relevant and robust indicators for ULF bands. But we will implement it anyway :)

Kind Regards,
Robin

**Pull request closed without merging**
